### ISSUE TITLE
`username` and `password` shouldn't be required when `token` and `userId` are provided

### ISSUE THREAD

**Issue by LilaRest** [junhoyeo/threads-api#132] opened 2023-07-12 22:07 UTC
Hi! 
I'm actually storing `token` and `userId` to disk to prevent requesting login again between restarts of my app.

While initializing the `ThreadsAPI` object, giving those to it without `username` and `password` will throw `Error: Username or password not set` when calling `publish() (and maybe on other methods, not tried yet).

However, I've quickly browsed the code of the `publish()` method and it seems that it doesn't require neither `username` nor the `password` as soon as `token` and `userId` are available.

As a current workaround I'm instanciating `ThreadsAPI` with dummy `username` and `password`: 
`new ThreadsAPI({ username: " ", password: " ", token: token, userID: userId });`

**Comment by junhoyeo** [comment] 2023-07-13 01:18
oh my god, nice point, thanks!

**Comment by cedriking** [comment] 2023-07-13 02:04
I've sent a PR fix for this. Seems the issue is only in `publish()`.

**Closed** 2023-07-13 02:55 UTC
Labels: bug

**Comment by junhoyeo** [comment] 2023-07-13 04:05
Deployed in [v1.4.1](https://github.com/junhoyeo/threads-api/releases/tag/v1.4.1) 🥳 
Thanks @cedriking @LilaRest 🙏

**Comment by LilaRest** [comment] 2023-07-13 08:41
Awesome, thanks @cedriking and @junhoyeo :)
